sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - $HOME/.cache/yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install

install:
  - yarn

script:
  - npm run build

git:
  depth: 1
